export const mostPopular = [
  {
    adult: false,
    backdrop_path: "/iPhDToxFzREctUA0ZQiYZamXsMy.jpg",
    genre_ids: [16, 10751, 35, 14],
    id: 508947,
    original_language: "en",
    original_title: "Turning Red",
    overview:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    popularity: 9962.298,
    poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    release_date: "2022-03-10",
    title: "Turning Red",
    video: false,
    vote_average: 7.5,
    vote_count: 880,
  },
  {
    adult: false,
    backdrop_path: "/h22eEPJpdS47JisaEPevdj48fVT.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 7841.281,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.2,
    vote_count: 10259,
  },
  {
    adult: false,
    backdrop_path: "/ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg",
    genre_ids: [28, 12, 35, 878],
    id: 696806,
    original_language: "en",
    original_title: "The Adam Project",
    overview:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.",
    popularity: 4698.679,
    poster_path: "/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    release_date: "2022-03-11",
    title: "The Adam Project",
    video: false,
    vote_average: 7,
    vote_count: 1052,
  },
  {
    adult: false,
    backdrop_path: "/2hGjmgZrS1nlsEl5PZorn7EsmzH.jpg",
    genre_ids: [28, 53],
    id: 823625,
    original_language: "en",
    original_title: "Blacklight",
    overview:
      "Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.",
    popularity: 2863.721,
    poster_path: "/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg",
    release_date: "2022-02-10",
    title: "Blacklight",
    video: false,
    vote_average: 5.7,
    vote_count: 178,
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    popularity: 2524.988,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",
    video: false,
    vote_average: 7.7,
    vote_count: 5507,
  },
  {
    adult: false,
    backdrop_path: "/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg",
    genre_ids: [80, 9648, 53],
    id: 414906,
    original_language: "en",
    original_title: "The Batman",
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    popularity: 2399.305,
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    release_date: "2022-03-01",
    title: "The Batman",
    video: false,
    vote_average: 7.9,
    vote_count: 2260,
  },
  {
    adult: false,
    backdrop_path: "/33wnBK5NxvuKQv0Cxo3wMv0eR7F.jpg",
    genre_ids: [27, 53],
    id: 833425,
    original_language: "en",
    original_title: "No Exit",
    overview:
      "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.",
    popularity: 2081.611,
    poster_path: "/5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg",
    release_date: "2022-02-25",
    title: "No Exit",
    video: false,
    vote_average: 6.5,
    vote_count: 253,
  },
  {
    adult: false,
    backdrop_path: "/yzH5zvuEzzsHLZnn0jwYoPf0CMT.jpg",
    genre_ids: [53, 28],
    id: 760926,
    original_language: "en",
    original_title: "Gold",
    overview:
      "In the not-too-distant future, two drifters traveling through the desert stumble across the biggest gold nugget ever found and the dream of immense wealth and greed takes hold. They hatch a plan to excavate their bounty, with one man leaving to secure the necessary tools while the other remains with the gold. The man who remains must endure harsh desert elements, ravenous wild dogs, and mysterious intruders, while battling the sinking suspicion that he has been abandoned to his fate.",
    popularity: 2006.897,
    poster_path: "/ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg",
    release_date: "2022-01-13",
    title: "Gold",
    video: false,
    vote_average: 6.5,
    vote_count: 135,
  },
  {
    adult: false,
    backdrop_path: "/7CamWBejQ9JQOO5vAghZfrFpMXY.jpg",
    genre_ids: [28, 53, 80],
    id: 928381,
    original_language: "fr",
    original_title: "Sans répit",
    overview:
      "After going to extremes to cover up an accident, a corrupt cop's life spirals out of control when he starts receiving threats from a mysterious witness.",
    popularity: 1450.199,
    poster_path: "/9MP21x0OPv0R72obd63tMHssmGt.jpg",
    release_date: "2022-02-25",
    title: "Restless",
    video: false,
    vote_average: 5.9,
    vote_count: 172,
  },
  {
    adult: false,
    backdrop_path: "/qBLEWvJNVsehJkEJqIigPsWyBse.jpg",
    genre_ids: [16, 10751, 14, 35, 12],
    id: 585083,
    original_language: "en",
    original_title: "Hotel Transylvania: Transformania",
    overview:
      "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    popularity: 1391.307,
    poster_path: "/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
    release_date: "2022-02-25",
    title: "Hotel Transylvania: Transformania",
    video: false,
    vote_average: 7,
    vote_count: 477,
  },
  {
    adult: false,
    backdrop_path: "/4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
    genre_ids: [28, 12, 53, 10752],
    id: 476669,
    original_language: "en",
    original_title: "The King's Man",
    overview:
      "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
    popularity: 1358.124,
    poster_path: "/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg",
    release_date: "2021-12-22",
    title: "The King's Man",
    video: false,
    vote_average: 7,
    vote_count: 2079,
  },
  {
    adult: false,
    backdrop_path: "/cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
    genre_ids: [16, 28, 14, 12],
    id: 768744,
    original_language: "ja",
    original_title:
      "僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション",
    overview:
      "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.",
    popularity: 1238.856,
    poster_path: "/4NUzcKtYPKkfTwKsLjwNt8nRIXV.jpg",
    release_date: "2021-08-06",
    title: "My Hero Academia: World Heroes' Mission",
    video: false,
    vote_average: 7.4,
    vote_count: 123,
  },
  {
    adult: false,
    backdrop_path: "/eG0oOQVsniPAuecPzDD1B1gnYWy.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 774825,
    original_language: "en",
    original_title: "The Ice Age Adventures of Buck Wild",
    overview:
      "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Buck's home: The Dinosaur World.",
    popularity: 1242.524,
    poster_path: "/zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg",
    release_date: "2022-01-28",
    title: "The Ice Age Adventures of Buck Wild",
    video: false,
    vote_average: 7.1,
    vote_count: 825,
  },
  {
    adult: false,
    backdrop_path: "/mruT954ve6P1zquaRs6XG0hA5k9.jpg",
    genre_ids: [53],
    id: 800510,
    original_language: "en",
    original_title: "Kimi",
    overview:
      "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.",
    popularity: 1249.194,
    poster_path: "/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
    release_date: "2022-02-10",
    title: "Kimi",
    video: false,
    vote_average: 6.3,
    vote_count: 274,
  },
  {
    adult: false,
    backdrop_path: "/i5dUmY2xRzgkmjHJYKNj8kPX1Xx.jpg",
    genre_ids: [37, 28],
    id: 928999,
    original_language: "en",
    original_title: "Desperate Riders",
    overview:
      "After Kansas Red rescues young Billy from a card-game shootout, the boy asks Red for help protecting his family from the outlaw Thorn, who’s just kidnapped Billy’s mother, Carol. As Red and Billy ride off to rescue Carol, they run into beautiful, tough-as-nails Leslie, who’s managed to escape Thorn’s men. The three race to stop Thorn’s wedding to Carol with guns a-blazing - but does she want to be rescued?",
    popularity: 1233.112,
    poster_path: "/7pYYGm1dWZGkbJuhcuaHD6nE6k7.jpg",
    release_date: "2022-02-25",
    title: "Desperate Riders",
    video: false,
    vote_average: 6.3,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
    genre_ids: [27, 9648, 53],
    id: 646385,
    original_language: "en",
    original_title: "Scream",
    overview:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    popularity: 1115.231,
    poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    release_date: "2022-01-12",
    title: "Scream",
    video: false,
    vote_average: 6.8,
    vote_count: 996,
  },
  {
    adult: false,
    backdrop_path: "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
    genre_ids: [878],
    id: 524434,
    original_language: "en",
    original_title: "Eternals",
    overview:
      "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
    popularity: 1262.041,
    poster_path: "/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg",
    release_date: "2021-11-03",
    title: "Eternals",
    video: false,
    vote_average: 7.2,
    vote_count: 4947,
  },
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [16, 35, 10751, 10402],
    id: 438695,
    original_language: "en",
    original_title: "Sing 2",
    overview:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    popularity: 1168.843,
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    release_date: "2021-12-01",
    title: "Sing 2",
    video: false,
    vote_average: 8.2,
    vote_count: 2326,
  },
  {
    adult: false,
    backdrop_path: "/pnZ9NMxRqbcJ2dPNROIoregruv5.jpg",
    genre_ids: [28, 80, 53],
    id: 753232,
    original_language: "en",
    original_title: "The Commando",
    overview:
      "An elite DEA agent returns home after a failed mission when his family makes an unexpected discovery in their house – a stash of money worth $3 million. They soon face the danger and threat of a newly released criminal and his crew, who will do whatever it takes to retrieve the money, including kidnap the agent’s daughters. Stakes are high and lives are at risk in this head-to-head battle as the agent stops at nothing to protect his family against the money-hungry criminals.",
    popularity: 1169.067,
    poster_path: "/mn1GYIQ1tvFuuu0YBNZBvrHyrkO.jpg",
    release_date: "2022-01-07",
    title: "The Commando",
    video: false,
    vote_average: 6.8,
    vote_count: 54,
  },
  {
    adult: false,
    backdrop_path: "/eVSa4TpyXbOdk9fXSD6OcORJGtv.jpg",
    genre_ids: [53],
    id: 803114,
    original_language: "en",
    original_title: "The Requin",
    overview:
      "A couple on a romantic getaway find themselves stranded at sea when a tropical storm sweeps away their villa. In order to survive, they are forced to fight the elements, while sharks circle below.",
    popularity: 1131.323,
    poster_path: "/i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg",
    release_date: "2022-01-28",
    title: "The Requin",
    video: false,
    vote_average: 4.8,
    vote_count: 80,
  },
];

export const trendingMovie = [
  {
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    release_date: "2021-12-15",
    adult: false,
    backdrop_path: "/h22eEPJpdS47JisaEPevdj48fVT.jpg",
    vote_count: 10259,
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.2,
    popularity: 7841.281,
    media_type: "movie",
  },
  {
    video: false,
    vote_average: 7.1,
    vote_count: 84,
    title: "Jackass Forever",
    adult: false,
    overview:
      "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.",
    release_date: "2022-02-01",
    id: 656663,
    backdrop_path: "/f2J8DpT5bqV0AiI9VVcfiuqKo5l.jpg",
    original_language: "en",
    original_title: "Jackass Forever",
    poster_path: "/ruHDFumJfW7F2vEqTZEQQ9xT7CA.jpg",
    genre_ids: [35, 99, 28],
    popularity: 290.982,
    media_type: "movie",
  },
  {
    release_date: "2022-03-18",
    adult: false,
    backdrop_path: "/hJjA3EY7yoT1djGyD20lM3WzgyM.jpg",
    genre_ids: [18, 9648, 53],
    vote_count: 172,
    original_language: "en",
    original_title: "Deep Water",
    id: 619979,
    title: "Deep Water",
    video: false,
    vote_average: 5.5,
    poster_path: "/6yRMyWwjuhKg6IU66uiZIGhaSc8.jpg",
    overview:
      "Vic and Melinda Van Allen are a couple in the small town of Little Wesley. Their loveless marriage is held together only by a precarious arrangement whereby, in order to avoid the messiness of divorce, Melinda is allowed to take any number of lovers as long as she does not desert her family.",
    popularity: 599.516,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/t7I942V5U1Ggn6OevN75u3sNYH9.jpg",
    genre_ids: [28, 53],
    id: 760868,
    original_language: "sv",
    original_title: "Svart krabba",
    overview:
      "To end an apocalyptic war and save her daughter, a reluctant soldier embarks on a desperate mission to cross a frozen sea carrying a top-secret cargo.",
    poster_path: "/mcIYHZYwUbvhvUt8Lb5nENJ7AlX.jpg",
    release_date: "2022-03-18",
    title: "Black Crab",
    video: false,
    vote_average: 6.3,
    vote_count: 112,
    popularity: 220.863,
    media_type: "movie",
  },
  {
    vote_average: 7.9,
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    release_date: "2022-03-01",
    adult: false,
    backdrop_path: "/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg",
    vote_count: 2260,
    genre_ids: [80, 9648, 53],
    id: 414906,
    original_language: "en",
    original_title: "The Batman",
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    title: "The Batman",
    video: false,
    popularity: 2399.305,
    media_type: "movie",
  },
  {
    genre_ids: [16, 10751, 35, 14],
    original_language: "en",
    original_title: "Turning Red",
    poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    title: "Turning Red",
    id: 508947,
    vote_average: 7.5,
    overview:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    release_date: "2022-03-10",
    vote_count: 880,
    adult: false,
    backdrop_path: "/iPhDToxFzREctUA0ZQiYZamXsMy.jpg",
    video: false,
    popularity: 9962.298,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/4YOpxmGyQZFELwLB7JqcpYKnmKw.jpg",
    genre_ids: [10751, 35],
    id: 691683,
    original_language: "en",
    original_title: "Cheaper by the Dozen",
    overview:
      "This remake of the beloved classic follows the raucous exploits of a blended family of 12, the Bakers, as they navigate a hectic home life while simultaneously managing their family business.",
    poster_path: "/qNRsouZh5zmhaE3n4QpLDXzy1gQ.jpg",
    release_date: "2022-03-18",
    title: "Cheaper by the Dozen",
    video: false,
    vote_average: 6.2,
    vote_count: 43,
    popularity: 232.677,
    media_type: "movie",
  },
  {
    release_date: "2022-03-11",
    adult: false,
    backdrop_path: "/ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg",
    genre_ids: [28, 12, 35, 878],
    original_language: "en",
    original_title: "The Adam Project",
    poster_path: "/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    title: "The Adam Project",
    video: false,
    vote_average: 7,
    id: 696806,
    vote_count: 1052,
    overview:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.",
    popularity: 4698.679,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/cc7Nmid20lcfNh1eucWdLKidi7s.jpg",
    genre_ids: [80, 18, 53],
    id: 850018,
    original_language: "en",
    original_title: "Windfall",
    overview:
      "A man breaks into a tech billionaire's empty vacation home, but things go sideways when the arrogant mogul and his wife arrive for a last-minute getaway.",
    poster_path: "/r3eGUCijDCNqwcP1Ri8AZyTbPzI.jpg",
    release_date: "2022-03-11",
    title: "Windfall",
    video: false,
    vote_average: 5.5,
    vote_count: 73,
    popularity: 68.718,
    media_type: "movie",
  },
  {
    poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    video: false,
    id: 646385,
    overview:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    release_date: "2022-01-12",
    title: "Scream",
    adult: false,
    backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
    vote_count: 996,
    genre_ids: [27, 9648, 53],
    vote_average: 6.8,
    original_language: "en",
    original_title: "Scream",
    popularity: 1115.231,
    media_type: "movie",
  },
  {
    vote_average: 4.8,
    overview:
      "At an elite New England university built on the site of a Salem-era gallows hill, two black women strive to find their place. Navigating politics and privilege, they encounter increasingly terrifying manifestations of the school's haunted past… and present.",
    release_date: "2022-03-18",
    id: 680829,
    adult: false,
    backdrop_path: "/bW0zTTdvc9zafc6hDEG1pMDuMCW.jpg",
    genre_ids: [27, 53, 18, 9648],
    vote_count: 18,
    original_language: "en",
    original_title: "Master",
    poster_path: "/gxbwRHsQ2v6DQv28ttp7pIx7Utj.jpg",
    title: "Master",
    video: false,
    popularity: 78.636,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/11BkXcbBWVX2eW08p5KTudxregE.jpg",
    genre_ids: [18],
    id: 946726,
    original_language: "tr",
    original_title: "Sen Yaşamaya Bak",
    overview:
      "Diagnosed with a terminal illness, a single mother encounters a suave bachelor as she grapples with the future of her headstrong six-year-old.",
    poster_path: "/eymTgzHgYretvL5mT7pwznX4p34.jpg",
    release_date: "2022-03-21",
    title: "In Good Hands",
    video: false,
    vote_average: 7.3,
    vote_count: 3,
    popularity: 49.221,
    media_type: "movie",
  },
  {
    vote_average: 7.1,
    overview:
      "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
    release_date: "2021-12-02",
    adult: false,
    backdrop_path: "/g0YNGpmlXsgHfhGnJz3c5uyzZ1B.jpg",
    vote_count: 1185,
    genre_ids: [80, 18, 53],
    id: 597208,
    original_language: "en",
    original_title: "Nightmare Alley",
    poster_path: "/vfn1feL0V9HNSXuLLpaxAW8O6LO.jpg",
    title: "Nightmare Alley",
    video: false,
    popularity: 1049.083,
    media_type: "movie",
  },
  {
    release_date: "2022-03-17",
    adult: false,
    backdrop_path: "/zQG1FYDqoWo2hYhE5GVZ1yrWSfh.jpg",
    genre_ids: [10751, 18],
    vote_count: 51,
    original_language: "en",
    original_title: "Rescued by Ruby",
    poster_path: "/tPlJEodEn0SSV4avo8KSawtlTlN.jpg",
    title: "Rescued by Ruby",
    video: false,
    vote_average: 7.3,
    id: 921655,
    overview:
      "Chasing his dream to join an elite K-9 unit, a state trooper partners with a fellow underdog: clever but naughty shelter pup Ruby. Based on a true story.",
    popularity: 254.054,
    media_type: "movie",
  },
  {
    vote_average: 7.3,
    overview:
      "Avery, a teenager with a tendency towards perfectionism, enlists her friend Larson to help her prepare for her first time with her long-distance boyfriend.",
    release_date: "2022-01-14",
    adult: false,
    backdrop_path: "/sqLNgWTMBhLBRY26SwwfWcSI5qq.jpg",
    vote_count: 22,
    genre_ids: [35, 10749],
    id: 803104,
    original_language: "en",
    original_title: "Sex Appeal",
    poster_path: "/mpwXOeSSQdBjUpyQqf6YHYbSTFO.jpg",
    title: "Sex Appeal",
    video: false,
    popularity: 73.578,
    media_type: "movie",
  },
  {
    genre_ids: [28, 53],
    original_language: "en",
    original_title: "Panama",
    poster_path: "/qpUBoMASmCxKsdNwX0XCTXvHzbF.jpg",
    title: "Panama",
    id: 628878,
    vote_average: 6.3,
    overview:
      "An ex-marine is hired by a defense contractor to travel to Panama to complete an arms deal. In the process he becomes involved with the U.S. invasion of Panama, and learns an important lesson about the true nature of political power.",
    release_date: "2022-03-17",
    vote_count: 15,
    adult: false,
    backdrop_path: "/trtFAmf4IcndxSh5tIfLwxPyW67.jpg",
    video: false,
    popularity: 97.967,
    media_type: "movie",
  },
  {
    id: 568124,
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    original_language: "en",
    original_title: "Encanto",
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    video: false,
    vote_average: 7.7,
    vote_count: 5507,
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    release_date: "2021-11-24",
    title: "Encanto",
    popularity: 2524.988,
    media_type: "movie",
  },
  {
    poster_path: "/7GcqdBKaMM9BWXWN07BirBMkcBF.jpg",
    video: false,
    id: 716612,
    overview:
      "During her Christmas holidays with the royal family at the Sandringham estate in Norfolk, England, Diana decides to leave her marriage to Prince Charles.",
    release_date: "2021-11-04",
    title: "Spencer",
    adult: false,
    backdrop_path: "/fdE7pXaGyaFI39dy3Fg59FSauNr.jpg",
    vote_count: 631,
    genre_ids: [18],
    vote_average: 7.1,
    original_language: "en",
    original_title: "Spencer",
    popularity: 94.34,
    media_type: "movie",
  },
  {
    id: 624860,
    adult: false,
    backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
    genre_ids: [878, 28, 12],
    title: "The Matrix Resurrections",
    original_language: "en",
    original_title: "The Matrix Resurrections",
    poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    video: false,
    vote_average: 6.8,
    overview:
      "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    vote_count: 3326,
    release_date: "2021-12-16",
    popularity: 840.171,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [16, 35, 10751, 10402],
    title: "Sing 2",
    original_language: "en",
    original_title: "Sing 2",
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    video: false,
    vote_average: 8.2,
    overview:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    release_date: "2021-12-01",
    vote_count: 2326,
    id: 438695,
    popularity: 1168.843,
    media_type: "movie",
  },
];
