const strings = {
  homeScreenTitle: "MovieDB",
  homeScreenNavigationButtonTitle: "Go to next screen",
  movieDetailScreenText: "Movie Detail",
  movieDetailNavigationButtonTitle: "Go Back",
  percentSymbol: "%",
  whatsPopular: "What's Popular",
  freeToWatch: "Free To Watch",
  today: "Today",
  trending: "Trending",
  errorMessage: "Sorry Couldn't fetch Data",
  streaming: "Streaming",
  onTV: "On TV",
  inTheatres: "In Theatres",
  forRent: "For Rent",
  userScore: "User Score",
  playTrailer: "Play Trailer",
  nr: "NR",
  us: "US",
  overview: "Overview",
  commaWithLeadingSpace: ", ",
  space: " ",
  errorMessageDetailScreen: "Could not fetch data, please try again",
};

export default strings;
